# Alert System Configuration Template

# Performance Alert Thresholds
alert_thresholds:
  drawdown_threshold: 0.10  # 10% maximum drawdown
  loss_streak: 5  # Alert after 5 consecutive losses
  daily_loss_limit: 1000.0  # Daily loss limit in account currency
  profit_target: 5000.0  # Daily profit target
  min_win_rate: 0.40  # Minimum acceptable win rate
  max_risk_exposure: 0.15  # Maximum portfolio risk exposure (15%)
  volatility_threshold: 0.02  # Alert on 2% price volatility increase
  trade_frequency_min: 5  # Minimum trades per hour
  trade_frequency_max: 20  # Maximum trades per hour

# Alert System Settings
alert_cooldown_minutes: 15  # Minimum time between same type alerts
max_alert_history: 1000  # Maximum number of alerts to keep in history
max_notification_history: 1000  # Maximum number of notifications to keep in history

# Email Notification Settings
email:
  enabled: true
  sender: "trading-bot@example.com"
  recipients:
    - "trader@example.com"
    - "analyst@example.com"
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "your-email@gmail.com"
  password: "your-app-specific-password"  # Use app-specific password for security

# Discord Notification Settings
discord:
  enabled: true
  webhook_url: "https://discord.com/api/webhooks/your-webhook-url"
  mention_role_id: "role-id-for-critical-alerts"  # Optional role to mention for critical alerts

# Telegram Notification Settings
telegram:
  enabled: true
  bot_token: "your-bot-token"
  chat_ids:  # List of chat IDs to send alerts to
    - "-1234567890"  # Group chat ID
    - "9876543210"   # Individual chat ID

# Alert Display Settings
display:
  timezone: "UTC"  # Timezone for alert timestamps
  date_format: "%Y-%m-%d %H:%M:%S"  # Date format for alert display
  currency_symbol: "$"  # Currency symbol for monetary values
  decimal_places: 2  # Number of decimal places for numeric values 