# Analysis Agent Configuration

# General settings
max_cache_size: 1000  # Maximum number of data points to keep in memory
historical_data_limit: 500  # Number of historical candles to request

# Strategy configurations
strategies:
  # Basic Technical Analysis Strategies
  moving_average_cross:
    enabled: true
    weight: 1.0
    parameters:
      fast_period: 10
      slow_period: 20

  rsi:
    enabled: true
    weight: 1.0
    parameters:
      period: 14
      overbought: 70
      oversold: 30

  bollinger_bands:
    enabled: true
    weight: 1.0
    parameters:
      period: 20
      std_dev: 2.0

  # Advanced Pattern Recognition Strategies
  directional_change:
    enabled: true
    weight: 1.2
    parameters:
      threshold: 0.02
      window_size: 20

  rsi_pca:
    enabled: true
    weight: 1.1
    parameters:
      components: 3
      window_size: 30

  volatility_hawkes:
    enabled: true
    weight: 1.0
    parameters:
      decay_factor: 0.1
      impact_factor: 0.5

  trendline:
    enabled: true
    weight: 1.2
    parameters:
      min_points: 3
      max_deviation: 0.02

  head_shoulders:
    enabled: true
    weight: 1.3
    parameters:
      min_pattern_length: 20
      max_pattern_length: 60

  # Market Structure Strategies
  market_profile:
    enabled: true
    weight: 1.1
    parameters:
      value_area_volume: 0.68
      num_profile_levels: 30

  harmonic_patterns:
    enabled: true
    weight: 1.2
    parameters:
      pattern_types: ["gartley", "butterfly", "bat", "crab"]
      tolerance: 0.05

  flags_pennants:
    enabled: true
    weight: 1.1
    parameters:
      min_pattern_bars: 10
      max_pattern_bars: 30

  # Advanced Analysis Strategies
  market_structure:
    enabled: true
    weight: 1.3
    parameters:
      swing_threshold: 0.02
      structure_period: 50

  mean_reversion:
    enabled: true
    weight: 1.0
    parameters:
      lookback_period: 20
      std_dev_threshold: 2.0

  volatility:
    enabled: true
    weight: 1.0
    parameters:
      period: 20
      atr_multiplier: 2.0

  trend_following:
    enabled: true
    weight: 1.2
    parameters:
      trend_period: 50
      momentum_period: 14

  # Specialized Strategies
  tvl_indicator:
    enabled: true
    weight: 1.1
    parameters:
      volume_factor: 1.5
      trend_factor: 1.0

  intramarket_difference:
    enabled: true
    weight: 1.0
    parameters:
      correlation_threshold: 0.7
      lookback_period: 30

  permutation_entropy:
    enabled: true
    weight: 1.0
    parameters:
      embedding_dimension: 3
      delay: 1

  vsa:
    enabled: true
    weight: 1.2
    parameters:
      volume_threshold: 1.5
      spread_factor: 1.2

  rolling_window:
    enabled: true
    weight: 1.0
    parameters:
      window_size: 20
      min_extremes: 3

  pip:
    enabled: true
    weight: 1.1
    parameters:
      vertical_threshold: 0.01
      horizontal_threshold: 5

# Signal combination settings
signal_thresholds:
  bullish: 0.2    # Threshold for bullish signals
  bearish: -0.2   # Threshold for bearish signals

# Performance optimization
optimization:
  update_interval: 1     # How often to update analysis (in seconds)
  batch_size: 100       # Number of candles to process in one batch
  parallel_processing: true  # Enable parallel strategy processing 